AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-discord-bot
  A Serverless Discord Bot template built with Discord Slash Commands and AWS SAM.

Parameters:
  BotTokenSecretArn:
    Type: String
    AllowedPattern: '^arn:aws:secretsmanager:[a-z0-9-]+:[0-9]{12}:secret:[a-zA-Z0-9\/_+=.@-]+$'
    ConstraintDescription: "Parameter BotTokenSecretArn must contain a valid Secrets Manager Secret ARN"

Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 3

Resources:
  CreateCommandsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/create_commands
      Description: "Function to create Discord Slash Commands"
      Handler: index.lambdaHandler
      Environment:
        Variables:
          BOT_TOKEN_SECRET_ARN: !Ref BotTokenSecretArn
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref BotTokenSecretArn

  CreateCommandsInvoker:
    Type: Custom::CreateCommandsInvoker
    Properties:
      ServiceToken: !GetAtt CreateCommandsFunction.Arn

  DiscordInteractionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  DiscordHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/handler
      Description: "Serverless Function to handle incoming Discord requests"
      Handler: app.lambdaHandler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref DiscordInteractionApi
            Path: /hello
            Method: post
      Environment:
        Variables:
          DISCORD_PUBLIC_KEY: '{{resolve:ssm:/serverless-discord-bot/prod/DISCORD_PUBLIC_KEY}}'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DiscordInteractionApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${DiscordInteractionApi}.execute-api.${AWS::Region}.amazonaws.com/prod/hello/"
  DiscordHandlerFunction:
    Description: "Discord Handler Lambda Function ARN"
    Value: !GetAtt DiscordHandlerFunction.Arn
  DiscordHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for Discord Handler function"
    Value: !GetAtt DiscordHandlerFunctionRole.Arn
